---
title: "03"
author: "Aubrey Odom"
date: "2024-07-11"
output: html_document
---

This file continues the data analysis from the cluster characterization step given the processed data.

# Setup
```{R setup}
suppressPackageStartupMessages({
  library(tidyverse) # data manipulation
  library(Seurat) # SC analysis
  library(limma) # Diff expression
  library(edgeR) # Diff expression
  library(patchwork) # Plotting
  library(ggplot2) # Plotting
  library(gridExtra) # Plotting
  library(randomcoloR) # Plotting
  library(ggiraphExtra)
  # devtools::install_github("ricardo-bion/ggradar")
  library(ggradar)
  library(reshape2)
})

fig_folder <- "~/altcells/singlecellseq/vitalia_scs_aro/figures_tm"
```

```{R}
data_labelled <- readRDS("/projectnb/altcells/singlecellseq/vitalia_scs_aro/processed_data/data_labelled_TM.RDS") |>
  PrepSCTFindMarkers( assay = "SCT")
```

# Finding differentially expressed genes (cluster biomarkers)

## Obtain the differentially expressed genes
This step should not be rerun to save computational power
```{R, eval = FALSE}
# find markers for every cluster compared to all remaining cells, report only the positive ones
all.markers <- FindAllMarkers(data_labelled, assay = "SCT", only.pos = TRUE)
saveRDS(all.markers,
file = "~/altcells/singlecellseq/vitalia_scs_aro/processed_data/all_markers_TM.RDS")
```

```{R}
all_markers <- readRDS("~/altcells/singlecellseq/vitalia_scs_aro/processed_data/all_markers_TM.RDS")

```

## Examine the markers
```{R}
preview_table <- all_markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
  arrange(desc(avg_log2FC))

table(preview_table$cluster)
preview_table
```
## Top 10
High = yellow, low = purple
```{R}
top10 <- all_markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup()

png(file.path(fig_folder, "heatmap.png"), units = "in", res = 300, width = 5, height = 6)

Seurat::DoHeatmap(subset(data_labelled, downsample = 1000), features = top10$gene)

dev.off()
```

# Cluster cell types

Based on UMAP, heatmap, and above characterizations

NEW: 0
0, 1, 3 - Fibroblasts

NEW: 1 
2 - Fibroblasts

NEW: 2
6 - fibroblasts, activated
8 - fibroblasts, activated

NEW: 3
15 - Fibroblasts, cardiomyocytes, senescent
12 - fibroblasts, cardiomyocytes, erythrocytes, senescent

NEW: 4
11 - fibroblasts, cardiomyocytes, adipocytes

NEW: 5
4 - Cardiomyocytes, fibroblasts

NEW: 6
17 - cardiomyocytes

NEW: 7
9 - endothelial

NEW: 8
5 - endothelial, cardiomyocytes

NEW: 9
16 - endothelial, cardiomyocytes

NEW: 10
7 - b cells

NEW: 11
10 -macrophages, monocytes

NEW: 12
13 - T cells, NK cells

NEW: 13
14 - fibroblasts, cardiomyocytes, (<50 macrophages, granulocytes, monocytes)

## Initial renaming
```{R}
all_clust_names <- levels(Idents(data_labelled))
new_cluster_ids <- vector(length(all_clust_names), mode = "list") %>%
  setNames(levels(Idents(data_labelled)))

new_cluster_ids$`0`<- new_cluster_ids$`1` <- new_cluster_ids$`3` <- 0
new_cluster_ids$`2` <- 1
new_cluster_ids$`6` <- new_cluster_ids$`8` <- 2
new_cluster_ids$`15` <- new_cluster_ids$`12` <- 3
new_cluster_ids$`11`<- 4
new_cluster_ids$`4` <-  5
new_cluster_ids$`17` <-  6
new_cluster_ids$`9` <-  7
new_cluster_ids$`5` <-  8
new_cluster_ids$`16` <-  9
new_cluster_ids$`7` <-  10
new_cluster_ids$`10` <-  11
new_cluster_ids$`13` <-  12
new_cluster_ids$`14` <-  13

celltypes <- c("C0" = "Fibroblasts",
               "C1" = "Fibroblasts",
               "C2" = "Fibroblasts, activated",
               "C3" = "Fibroblasts / Cardiomyocytes",
               "C4" = "Fibroblasts / Cardiomyocytes",
               "C5" = "Cardiomyocytes / Fibroblasts",
               "C6" = "Cardiomyocytes",
               "C7" = "Endothelial",
               "C8" = "Endothelial / Cardiomyocytes",
               "C9" = "Endothelial / Cardiomyocytes",
               "C10" = "B cells",
               "C11" = "Macrophages / Monocytes",
               "C12" = "T cells / NK cells",
               "C13" = "Mixed")

data_reclustered <- RenameIdents(data_labelled, new_cluster_ids)
data_reclustered$clusters <- Idents(data_reclustered) |>
  paste() |> as.numeric()
data_reclustered$celltype <- Idents(data_reclustered) %>%
  factor(levels = seq_along(unique(Idents(data_reclustered))) - 1, labels = celltypes)
data_reclustered$integrated_snn_res.0.4 <- data_reclustered$clusters
data_reclustered$seurat_clusters <- data_reclustered$clusters

rm(data_labelled)
```

# Export reclustered data
```{R}
dat_save <- "~/altcells/singlecellseq/vitalia_scs_aro/processed_data"
saveRDS(data_clustered, file.path(dat_save, "data_reclustered.RDS"))
```

